services:
  backend:
    build: backend
    volumes:
      - ./backend:/code
    environment:
      UWSGI_PY_AUTORELOAD: 1
      ENABLE_DOCS: 1

  db:
    ports:
      - '127.0.0.1:5432:5432'

  frontend:
    build: frontend
    volumes:
      - ./frontend:/home/node
    working_dir: /home/node
    command:
      - sh
      - -c
      - |
        {
          apk add --no-cache socat &&
          rm -f /run/nuxt.sock &&
          corepack enable &&
          pnpm install
        } || exit 1
        socat \
          UNIX-LISTEN:/run/nuxt.sock,fork,reuseaddr,mode=660,group=$$NITRO_SOCKET_GID \
          TCP:127.0.0.1:3000 \
        &
        exec pnpm dev

  proxy:
    stop_signal: SIGTERM
