[tool.mypy]
strict = true
files = ['backend', 'tests']

[tool.pytest.ini_options]
norecursedirs = ['.*', 'env']
addopts = [
    '-Werror',
    '--cov=backend',
    '--cov-report=term-missing:skip-covered',
    '--color=yes',
]

[tool.ruff]
line-length = 79

[tool.ruff.lint]
extend-select = ["E", "W", "C"]
preview = true
